=== RUN   TestBoolFromLong
--- PASS: TestBoolFromLong (0.05s)
=== RUN   TestBoolCheck
--- PASS: TestBoolCheck (0.04s)
=== RUN   TestPyByteArrayCheck
--- PASS: TestPyByteArrayCheck (0.05s)
=== RUN   TestPyByteArrayAsString
--- PASS: TestPyByteArrayAsString (0.05s)
=== RUN   TestPyByteArrayResize
--- PASS: TestPyByteArrayResize (0.04s)
=== RUN   TestPyByteArrayConcat
--- PASS: TestPyByteArrayConcat (0.05s)
=== RUN   TestPyByteArrayFromObject
--- PASS: TestPyByteArrayFromObject (0.05s)
=== RUN   TestBytesCheck
--- PASS: TestBytesCheck (0.04s)
=== RUN   TestBytesFromAsString
--- PASS: TestBytesFromAsString (0.00s)
=== RUN   TestBytesSize
--- PASS: TestBytesSize (0.00s)
=== RUN   TestBytesConcat
--- PASS: TestBytesConcat (0.00s)
=== RUN   TestBytesConcatAndDel
--- PASS: TestBytesConcatAndDel (0.00s)
=== RUN   TestComplex
--- PASS: TestComplex (0.00s)
=== RUN   TestDict
--- PASS: TestDict (0.00s)
=== RUN   TestErrorSetString
--- PASS: TestErrorSetString (0.00s)
=== RUN   TestErrorSetObject
BaseException: test message
--- PASS: TestErrorSetObject (0.00s)
=== RUN   TestErrorSetNone
BaseException
--- PASS: TestErrorSetNone (0.00s)
=== RUN   TestErrorSetObjectEx
BaseException: test message
--- PASS: TestErrorSetObjectEx (0.00s)
=== RUN   TestErrorWriteUnraisable
Exception ignored in: 'unraisable exception'
--- PASS: TestErrorWriteUnraisable (0.00s)
=== RUN   TestErrorBadArgument
--- PASS: TestErrorBadArgument (0.00s)
=== RUN   TestErrorNoMemory
--- PASS: TestErrorNoMemory (0.00s)
=== RUN   TestErrorBadInternalCall
--- PASS: TestErrorBadInternalCall (0.00s)
=== RUN   TestErrorImportError
--- PASS: TestErrorImportError (0.00s)
=== RUN   TestErrorSyntax
--- PASS: TestErrorSyntax (0.00s)
=== RUN   TestErrorSyntaxEx
--- PASS: TestErrorSyntaxEx (0.00s)
=== RUN   TestErrorSyntaxLocation
--- PASS: TestErrorSyntaxLocation (0.00s)
=== RUN   TestErrorExceptionMatches
--- PASS: TestErrorExceptionMatches (0.00s)
=== RUN   TestErrorGivenExceptionMatches
--- PASS: TestErrorGivenExceptionMatches (0.00s)
=== RUN   TestErrorFetchRestore
--- PASS: TestErrorFetchRestore (0.00s)
=== RUN   TestErrorNormalizeExceptionRestore
--- PASS: TestErrorNormalizeExceptionRestore (0.00s)
=== RUN   TestErrorGetSetExcInfo
--- PASS: TestErrorGetSetExcInfo (0.00s)
=== RUN   TestExceptionNew
--- PASS: TestExceptionNew (0.00s)
=== RUN   TestExceptionNewDoc
--- PASS: TestExceptionNewDoc (0.00s)
=== RUN   TestExceptionContext
--- PASS: TestExceptionContext (0.00s)
=== RUN   TestPyFloatCheck
--- PASS: TestPyFloatCheck (0.00s)
=== RUN   TestPyFloatFromAsDouble
--- PASS: TestPyFloatFromAsDouble (0.00s)
=== RUN   TestPyFloatFromAsString
--- PASS: TestPyFloatFromAsString (0.00s)
=== RUN   TestPyFloatMinMax
--- PASS: TestPyFloatMinMax (0.00s)
=== RUN   TestPyFloatInfo
--- PASS: TestPyFloatInfo (0.00s)
=== RUN   TestRunFile
--- PASS: TestRunFile (0.00s)
=== RUN   TestRunString
--- PASS: TestRunString (0.00s)
=== RUN   TestPyMain
--- PASS: TestPyMain (0.01s)
=== RUN   TestModuleCheck
--- PASS: TestModuleCheck (0.05s)
=== RUN   TestModuleNew
--- PASS: TestModuleNew (0.00s)
=== RUN   TestModuleNewObject
--- PASS: TestModuleNewObject (0.00s)
=== RUN   TestModuleGetDict
--- PASS: TestModuleGetDict (0.00s)
=== RUN   TestModuleGetName
--- PASS: TestModuleGetName (0.00s)
=== RUN   TestModuleGetNameObject
--- PASS: TestModuleGetNameObject (0.00s)
=== RUN   TestModuleGetState
--- PASS: TestModuleGetState (0.00s)
=== RUN   TestModuleGetFilenameObject
--- PASS: TestModuleGetFilenameObject (0.04s)
=== RUN   TestAttrString
--- PASS: TestAttrString (0.00s)
=== RUN   TestAttr
--- PASS: TestAttr (0.00s)
=== RUN   TestRichCompareBool
--- PASS: TestRichCompareBool (0.00s)
=== RUN   TestRichCompare
--- PASS: TestRichCompare (0.00s)
=== RUN   TestRepr
--- PASS: TestRepr (0.00s)
=== RUN   TestStr
--- PASS: TestStr (0.00s)
=== RUN   TestASCII
--- PASS: TestASCII (0.00s)
=== RUN   TestCallable
--- PASS: TestCallable (0.00s)
=== RUN   TestCallMethod
--- PASS: TestCallMethod (0.00s)
=== RUN   TestIsTrue
--- PASS: TestIsTrue (0.00s)
=== RUN   TestNot
--- PASS: TestNot (0.00s)
=== RUN   TestLength
--- PASS: TestLength (0.00s)
=== RUN   TestLengthHint
--- PASS: TestLengthHint (0.00s)
=== RUN   TestObjectItem
--- PASS: TestObjectItem (0.00s)
=== RUN   TestReprEnterLeave
--- PASS: TestReprEnterLeave (0.00s)
=== RUN   TestIsSubclass
--- PASS: TestIsSubclass (0.00s)
=== RUN   TestHash
--- PASS: TestHash (0.00s)
=== RUN   TestObjectType
--- PASS: TestObjectType (0.00s)
=== RUN   TestHashNotImplemented
--- PASS: TestHashNotImplemented (0.00s)
=== RUN   TestObjectIter
--- PASS: TestObjectIter (0.00s)
=== RUN   TestRecursion
--- PASS: TestRecursion (0.00s)
=== RUN   TestReflectionBuiltins
--- PASS: TestReflectionBuiltins (0.00s)
=== RUN   TestReflectionLocals
--- PASS: TestReflectionLocals (0.00s)
=== RUN   TestReflectionGlobals
--- PASS: TestReflectionGlobals (0.00s)
=== RUN   TestReflectionFuncName
--- PASS: TestReflectionFuncName (0.00s)
=== RUN   TestReflectionFuncDesc
--- PASS: TestReflectionFuncDesc (0.00s)
=== RUN   TestSysGetSetObject
--- PASS: TestSysGetSetObject (0.00s)
=== RUN   TestSysWarnOption
Exception ignored in: <module 'threading' from '/home/ella/.pyenv/versions/3.5.9/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/home/ella/.pyenv/versions/3.5.9/lib/python3.5/threading.py", line 1287, in _shutdown
    assert tlock.locked()
SystemError: <built-in method locked of _thread.lock object at 0x7f70445e0fa8> returned a result with an error set
--- PASS: TestSysWarnOption (0.12s)
=== RUN   TestSysXOption
--- PASS: TestSysXOption (0.04s)
=== RUN   TestSysPath
--- PASS: TestSysPath (0.00s)
=== RUN   TestThreadInitialization
--- PASS: TestThreadInitialization (0.00s)
=== RUN   TestGIL
--- PASS: TestGIL (0.00s)
=== RUN   TestThreadState
--- PASS: TestThreadState (0.00s)
=== RUN   TestThreadSaveRestore
--- PASS: TestThreadSaveRestore (0.00s)
=== RUN   TestTupleCheck
--- PASS: TestTupleCheck (0.00s)
=== RUN   TestTupleNew
--- PASS: TestTupleNew (0.00s)
=== RUN   TestTupleSize
--- PASS: TestTupleSize (0.00s)
=== RUN   TestTupleGetSetItem
--- PASS: TestTupleGetSetItem (0.00s)
=== RUN   TestTupleGetSlice
--- PASS: TestTupleGetSlice (0.00s)
=== RUN   TestTypeCheck
--- PASS: TestTypeCheck (0.00s)
=== RUN   TestUnicodeNew
--- PASS: TestUnicodeNew (0.00s)
=== RUN   TestUnicodeFromString
--- PASS: TestUnicodeFromString (0.00s)
=== RUN   TestUnicodeFromEncodedObject
--- PASS: TestUnicodeFromEncodedObject (0.00s)
=== RUN   TestUnicodeChar
--- PASS: TestUnicodeChar (0.00s)
=== RUN   TestUnicodeFill
--- PASS: TestUnicodeFill (0.00s)
=== RUN   TestUnicodeCopyCharacters
--- PASS: TestUnicodeCopyCharacters (0.00s)
=== RUN   TestUnicodeSubstring
--- PASS: TestUnicodeSubstring (0.00s)
=== RUN   TestWarnEx
--- PASS: TestWarnEx (0.00s)
=== RUN   TestWarnExplicitObject
test.py:4: RuntimeError: test warning
--- PASS: TestWarnExplicitObject (0.00s)
=== RUN   TestWarnExplicit
test.py:4: RuntimeError: test warning
--- PASS: TestWarnExplicit (0.00s)
PASS
ok      github.com/jshiwam/cpy3x/pycore 0.666s

MRS-Fail
MS-run
MR-run
SR-run

=======================
The above warning was silenced using PyErr_Clear()

================================================================

After adding lifecycle.go

Probably because of Calling functions such as GetProgramName before PyInititalize()

Ref:

Note The following functions should not be called before Py_Initialize(): Py_EncodeLocale(), Py_GetPath(), Py_GetPrefix(), Py_GetExecPrefix(), Py_GetProgramFullPath(), Py_GetPythonHome(), Py_GetProgramName() and PyEval_InitThreads().

Error 1


--- PASS: TestInitialization (0.13s)
=== RUN   TestInitializationEx
--- PASS: TestInitializationEx (0.07s)
=== RUN   TestProgramName
    lifecycle_test.go:35: 
                Error Trace:    /home/ella/dev/scribble/cpy3x/pycore/lifecycle_test.go:35
                Error:          Expected nil, but got: &errors.errorString{s:"fail to call Py_EncodeLocale"}
                Test:           TestProgramName
--- FAIL: TestProgramName (0.00s)
=== RUN   TestPrefix
--- PASS: TestPrefix (0.00s)

Error 2 :

--- PASS: TestInitialization (0.05s)
=== RUN   TestInitializationEx
--- PASS: TestInitializationEx (0.05s)
=== RUN   TestProgramName
--- PASS: TestProgramName (0.00s)
=== RUN   TestPrefix
--- PASS: TestPrefix (0.00s)
=== RUN   TestExecPrefix
--- PASS: TestExecPrefix (0.00s)
=== RUN   TestProgramFullPath
--- PASS: TestProgramFullPath (0.00s)
=== RUN   TestPath
--- PASS: TestPath (0.00s)
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
=== RUN   TestPlatform
--- PASS: TestPlatform (0.00s)
=== RUN   TestCopyright
--- PASS: TestCopyright (0.00s)
=== RUN   TestCompiler
--- PASS: TestCompiler (0.00s)
=== RUN   TestBuildInfo
--- PASS: TestBuildInfo (0.00s)
=== RUN   TestPythonHome
--- PASS: TestPythonHome (0.00s)
=== RUN   TestSetArgv
Fatal Python error: Py_Initialize: can't initialize sys

Current thread 0x00007f3a73232740 (most recent call first):
SIGABRT: abort
PC=0x7f3a732cba7c m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 62 [syscall]:
runtime.cgocall(0x5da280, 0xc0000406f8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000406d0 sp=0xc000040698 pc=0x423fbc
github.com/jshiwam/cpy3x/pycore._Cfunc_Py_Initialize()
        _cgo_gotypes.go:4985 +0x45 fp=0xc0000406f8 sp=0xc0000406d0 pc=0x5c7305
github.com/jshiwam/cpy3x/pycore.Py_Initialize(...)
        /home/ella/dev/scribble/cpy3x/pycore/lifecycle.go:22
github.com/jshiwam/cpy3x/pycore.TestSetArgv(0xc00016dd40?)
        /home/ella/dev/scribble/cpy3x/pycore/lifecycle_test.go:119 +0x25 fp=0xc000040770 sp=0xc0000406f8 pc=0x5b8ae5
testing.tRunner(0xc0001731e0, 0x7d7598)
        /usr/local/go/src/testing/testing.go:1439 +0x102 fp=0xc0000407c0 sp=0xc000040770 pc=0x4eb942
testing.(*T).Run.func1()
        /usr/local/go/src/testing/testing.go:1486 +0x2a fp=0xc0000407e0 sp=0xc0000407c0 pc=0x4ec7ea
runtime.goexit()


===========
The above error is resolved by not using PySet_Path in TestPath. We are just checking for Py_GetPath there.

What is the Reason ?

================
<!-- Why does nil gets appended to everything that we set in 3.5  -->
 RUN   TestPath
    lifecycle_test.go:92: default Path /home/ella/.pyenv/versions/3.5.9/lib/python35.zip:/home/ella/.pyenv/versions/3.5.9/lib/python3.5:/home/ella/.pyenv/versions/3.5.9/lib/python3.5/plat-linux:/home/ella/.pyenv/versions/3.5.9/lib/python3.5/lib-dynload
    lifecycle_test.go:101: /home/ella/.pyenv/versions/3.5.9/lib/python35.zip:/home/ella/.pyenv/versions/3.5.9/lib/python3.5:/home/ella/.pyenv/versions/3.5.9/lib/python3.5/plat-linux:/home/ella/.pyenv/versions/3.5.9/lib/python3.5/lib-dynload <nil>
    lifecycle_test.go:101:  <nil>
    lifecycle_test.go:101: /home/ella/.pyenv/shims/python3 <nil>
    lifecycle_test.go:101: /home/ella/.pyenv/versions/3.5.9 <nil>
    lifecycle_test.go:101: /home/ella/.pyenv/versions/3.5.9 <nil>
    lifecycle_test.go:101: ������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������򢥳Q <nil>
--- PASS: TestPath (0.00s)
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
=== RUN   TestPlatform
--- PASS: TestPlatform (0.00s)
=== RUN   TestCopyright
--- PASS: TestCopyright (0.00s)
=== RUN   TestCompiler
--- PASS: TestCompiler (0.00s)
=== RUN   TestBuildInfo
--- PASS: TestBuildInfo (0.00s)
=== RUN   TestSetArgv
Fatal Python error: Py_Initialize: can't initialize sys